name: "build-apps"
on:
  push:
    branches:
      - feature/update-workflow
    tags:
      - "*"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  BEFORE_SHA: ${{ github.event.before }}
  BOSSY_ECR_REGISTRY: public.ecr.aws/h1u4b2i4/cloudposse/bossy
  BOSSY_TEST_TAG: bossy:test
  IAM_ROLE_ARN: arn:aws:iam::847349463865:role/cplive-core-ue1-public-ecr-public-github-action
  IAM_ROLE_SEESION_NAME: cloudposse/bossy/ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ##################################################
      # Setup GHA Dependencies
      # docker context must be created prior to setting up Docker Buildx
      # https://github.com/actions-runner-controller/actions-runner-controller/issues/893
      ##################################################
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Set up Docker Buildx (required for docker/build-push-action)
        uses: docker/setup-buildx-action@v2

      ##################################################
      # Configure AWS
      ##################################################
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          role-session-name: ${{ env.IAM_ROLE_SESSION_NAME }}
      - name: Login to Public Amazon ECR
        run: |
          aws ecr-public get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin public.ecr.aws
        shell: bash

      ##################################################
      # Checkout the repository
      ##################################################
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch main branch so we can compare SHA
        run: git fetch origin main

      ##################################################
      # Install App Dependencies, Build, Lint, and Test
      ##################################################
      - name: Install Dependencies
        run: yarn install

      - name: Lint Affected Projects
        shell: bash
        run: npx nx affected --target=lint --base=$BEFORE_SHA

      - name: Test Affected Projects
        shell: bash
        run: npx nx affected --target=test --base=$BEFORE_SHA

      - name: Build Affected Projects
        shell: bash
        run: npx nx affected --target=build --base=$BEFORE_SHA #--base=remotes/origin/main

      ##################################################
      # Build and Push Bossy Docker Image
      ##################################################
      - name: Show Tags
        if: github.ref == 'refs/tags/'*
        run: |
          echo "${GITHUB_REF:10}"

      - name: Build bossy Docker image
        id: docker_build_tagged
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: apps/bossy/Dockerfile
          push: true
          tags: ${{ env.BOSSY_ECR_REGISTRY }}:${{github.sha}}
