name: "build-apps"
on:
  push:
    branches:
      - feature/update-workflow

env:
  BEFORE_SHA: ${{ github.event.before }}
  GITHUB_CONTEXT: ${{ toJson(github) }} # TODO: Remove after testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # TODO: Remove after testing
      - run: echo "$GITHUB_CONTEXT"

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: git fetch origin main
      - run: yarn install

      - name: run nx affected lint
        shell: bash
        run: npx nx affected --target=lint --base=$BEFORE_SHA

      - name: run nx affected test
        shell: bash
        run: npx nx affected --target=test --base=$BEFORE_SHA

      - name: run nx affected build
        shell: bash
        run: npx nx affected --target=build --base=$BEFORE_SHA #--base=remotes/origin/main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
