name: "build-apps"
on: push

env:
  BEFORE_SHA: ${{ github.event.before }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: git fetch origin main
      - run: yarn install
